package org.example.thewitcher.model.game;

public enum GameState {
    MAP,
    INVENTORY,
    INVENTORY_ITEM_ACTION_MENU,
    INVENTORY_INSPECT_ITEM,
    INTERACTION_ARMORER,
    INTERACTION_INNKEEPER,
    INTERACTION_BLACKSMITH,
    INTERACTION_MERCHANT,
    INTERACTION_SORCERESS,
    BATTLE,
    GAME_OVER,
    PAUSE_MENU
}
